### ISSUE TITLE
리뷰!

### ISSUE THREAD

**Issue by taelee42** [eunhyulkim/ft_factorization#2]
아랫분이 언급하신것 이외에는 특별한 에러사항을 찾지 못했습니다.
모든 경우에서 잘 출력되는 것을 확인했습니다.

특히 함수 하나당 25줄을 넘지 않으면서 함수 5개로 만드신것에 놀랐습니다.

또한 Makefile에서 색을 활용한 점이 인상깊었습니다.
나중에 제 코드에 적용하고 싶네요.

코드 잘 봤고 수고 많으셨습니다.~

**Comment by eunhyulkim** [comment]
c나 makefile에 색을 넣으니까 소소한 환기가 되더라고요. 리뷰 감사드립니다!
