### ISSUE TITLE
ft_factorization 함수의 리턴 타입 관련

### ISSUE THREAD

**Issue by cos18** [eunhyulkim/ft_factorization#3]
https://github.com/eunhyulkim/ft_factorization/blob/7218b7b367c4a8643dd0cea931ba1616d1f3004c/factorization.c#L83-L110

ft_factorization의 리턴값을 int로 지정해주셨는데, 굳이 int일 필요가 있나 싶습니다. 코드를 확인해보니 리턴값을 다른 함수에서 활용하거나 에러 status로 사용되는 것은 아닌거 같은데, 그냥 void로 깔끔하게 수정을 한다면 95, 109번째 줄의 리턴을 값을 반환하는 것 없이 `return ;`으로 처리하면 코드를 보기 좀 더 깔끔하지 않았나 생각이 듭니다. (추가적인 define도 할 필요도 없기도 하고요)

사실 이 사소한 점 말고는 읽기 좋았던 코드인 것 같습니다. 수고하셨습니다.

**Comment by eunhyulkim** [comment]
안녕하세요. 소수로 인해 리턴하는 케이스와 소인수분해를 끝내고 리턴하는 케이스를 가시적으로 구분하기 위해 값은 같지만 매크로로 처리했는데, 말씀을 듣고보니 사용하지 않을 리턴값이 있고, 거기다가 두 가지 형태로 있어서 오히려 읽으시는 데 불편함을 드렸구나 싶네요. 확실히 사용하지 않을 리턴값은 없애는 게 맞는 것 같습니다. 리뷰 감사드립니다!
